/**
 * In-memory fallback data matching Prisma schema.
 * Used when PostgreSQL is unavailable (local demo / CI).
 * Run `docker compose up -d && npx prisma migrate dev && npx prisma db seed` for live DB.
 */

import type {
  Blocker,
  Engineer,
  EngineerSkill,
  Initiative,
  Risk,
  Skill,
  Track,
  TrackSkillRequirement,
  WeeklyStatus,
} from "@prisma/client";

const now = new Date();
const weekStart = new Date("2026-06-30T00:00:00.000Z");

export const fallbackInitiatives: Initiative[] = [
  {
    id: "init-1",
    name: "Platform Modernization",
    businessGoal: "Reduce infra cost 30% and improve deployment velocity",
    owner: "VP Engineering",
    status: "AMBER",
    progressPercentage: 55,
    confidence: "MEDIUM",
    targetDate: new Date("2026-12-31"),
    leadershipAsk: "Approve Q4 infra budget for Kafka upgrade",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "init-2",
    name: "Checkout Conversion",
    businessGoal: "Increase mobile checkout conversion by 15%",
    owner: "VP Product",
    status: "AMBER",
    progressPercentage: 42,
    confidence: "MEDIUM",
    targetDate: new Date("2026-09-30"),
    leadershipAsk: "Temp mobile engineer for 2 sprints",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "init-3",
    name: "Data Platform Reliability",
    businessGoal: "99.9% SLA on core analytics pipelines",
    owner: "Director of Data",
    status: "RED",
    progressPercentage: 35,
    confidence: "LOW",
    targetDate: new Date("2026-10-15"),
    leadershipAsk: "VP Eng approval for $45K infra spend",
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackTracks: Track[] = [
  {
    id: "trk-1",
    initiativeId: "init-1",
    name: "API Gateway Modernization",
    description: "Event-driven gateway replacement",
    ownerEm: "Alex Rivera",
    ownerPm: "Sam Chen",
    techLead: "Morgan Lee",
    status: "GREEN",
    progressPercentage: 62,
    confidence: "HIGH",
    startDate: new Date("2026-04-01"),
    targetDate: new Date("2026-09-15"),
    effortEstimateDays: 68,
    actualEffortDays: 42,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-2",
    initiativeId: "init-1",
    name: "Observability Stack Upgrade",
    description: "Unified tracing and alerting",
    ownerEm: "Alex Rivera",
    ownerPm: "Sam Chen",
    techLead: "Morgan Lee",
    status: "GREY",
    progressPercentage: 10,
    confidence: "HIGH",
    startDate: new Date("2026-07-01"),
    targetDate: new Date("2026-11-15"),
    effortEstimateDays: 36,
    actualEffortDays: 4,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-3",
    initiativeId: "init-1",
    name: "CI/CD Pipeline Optimization",
    description: "Reduce build times and flakiness",
    ownerEm: "Alex Rivera",
    ownerPm: "Sam Chen",
    techLead: "Riley Patel",
    status: "GREEN",
    progressPercentage: 78,
    confidence: "HIGH",
    startDate: new Date("2026-03-01"),
    targetDate: new Date("2026-08-01"),
    effortEstimateDays: 45,
    actualEffortDays: 35,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-4",
    initiativeId: "init-2",
    name: "Mobile Checkout Redesign",
    description: "End-to-end checkout flow",
    ownerEm: "Jordan Kim",
    ownerPm: "Taylor Brooks",
    techLead: "Casey Nguyen",
    status: "AMBER",
    progressPercentage: 45,
    confidence: "MEDIUM",
    startDate: new Date("2026-05-01"),
    targetDate: new Date("2026-08-30"),
    effortEstimateDays: 56,
    actualEffortDays: 25,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-5",
    initiativeId: "init-2",
    name: "Payment SDK Integration",
    description: "New payment provider support",
    ownerEm: "Jordan Kim",
    ownerPm: "Taylor Brooks",
    techLead: "Casey Nguyen",
    status: "GREEN",
    progressPercentage: 85,
    confidence: "HIGH",
    startDate: new Date("2026-04-15"),
    targetDate: new Date("2026-07-15"),
    effortEstimateDays: 30,
    actualEffortDays: 26,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-6",
    initiativeId: "init-2",
    name: "A/B Testing Framework",
    description: "Experimentation platform for checkout",
    ownerEm: "Jordan Kim",
    ownerPm: "Taylor Brooks",
    techLead: "Avery Johnson",
    status: "GREEN",
    progressPercentage: 70,
    confidence: "HIGH",
    startDate: new Date("2026-05-15"),
    targetDate: new Date("2026-08-15"),
    effortEstimateDays: 25,
    actualEffortDays: 18,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-7",
    initiativeId: "init-3",
    name: "Data Pipeline Reliability",
    description: "SLA-backed pipelines with auto-recovery",
    ownerEm: "Alex Rivera",
    ownerPm: "Sam Chen",
    techLead: "Morgan Lee",
    status: "RED",
    progressPercentage: 38,
    confidence: "LOW",
    startDate: new Date("2026-04-01"),
    targetDate: new Date("2026-10-01"),
    effortEstimateDays: 44,
    actualEffortDays: 17,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "trk-8",
    initiativeId: "init-3",
    name: "Analytics Recovery Dashboard",
    description: "Self-serve pipeline health visibility",
    ownerEm: "Alex Rivera",
    ownerPm: "Sam Chen",
    techLead: "Quinn Martinez",
    status: "GREY",
    progressPercentage: 5,
    confidence: "MEDIUM",
    startDate: null,
    targetDate: new Date("2026-11-01"),
    effortEstimateDays: 20,
    actualEffortDays: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackSkills: Skill[] = [
  { id: "sk-1", name: "Backend", category: "Engineering", createdAt: now },
  { id: "sk-2", name: "Frontend", category: "Engineering", createdAt: now },
  { id: "sk-3", name: "Mobile", category: "Engineering", createdAt: now },
  { id: "sk-4", name: "DevOps", category: "Engineering", createdAt: now },
  { id: "sk-5", name: "System Design", category: "Engineering", createdAt: now },
  { id: "sk-6", name: "Observability", category: "Engineering", createdAt: now },
  { id: "sk-7", name: "Data Engineering", category: "Engineering", createdAt: now },
  { id: "sk-8", name: "Payments", category: "Domain", createdAt: now },
];

export const fallbackEngineers: Engineer[] = [
  { id: "eng-1", name: "Morgan Lee", role: "lead", level: "IC5", manager: "Alex Rivera", availabilityPercentage: 88, location: "SF", createdAt: now, updatedAt: now },
  { id: "eng-2", name: "Casey Nguyen", role: "lead", level: "IC5", manager: "Jordan Kim", availabilityPercentage: 75, location: "NYC", createdAt: now, updatedAt: now },
  { id: "eng-3", name: "Riley Patel", role: "engineer", level: "IC4", manager: "Alex Rivera", availabilityPercentage: 100, location: "SF", createdAt: now, updatedAt: now },
  { id: "eng-4", name: "Quinn Martinez", role: "engineer", level: "IC4", manager: "Alex Rivera", availabilityPercentage: 75, location: "Remote", createdAt: now, updatedAt: now },
  { id: "eng-5", name: "Avery Johnson", role: "engineer", level: "IC3", manager: "Jordan Kim", availabilityPercentage: 88, location: "Austin", createdAt: now, updatedAt: now },
  { id: "eng-6", name: "Drew Wilson", role: "engineer", level: "IC3", manager: "Jordan Kim", availabilityPercentage: 63, location: "Remote", createdAt: now, updatedAt: now },
  { id: "eng-7", name: "Sam Okonkwo", role: "engineer", level: "IC4", manager: "Alex Rivera", availabilityPercentage: 100, location: "London", createdAt: now, updatedAt: now },
  { id: "eng-8", name: "Jamie Foster", role: "engineer", level: "IC3", manager: "Jordan Kim", availabilityPercentage: 50, location: "NYC", createdAt: now, updatedAt: now },
  { id: "eng-9", name: "Priya Sharma", role: "engineer", level: "IC4", manager: "Alex Rivera", availabilityPercentage: 88, location: "SF", createdAt: now, updatedAt: now },
  { id: "eng-10", name: "Chris Taylor", role: "engineer", level: "IC3", manager: "Alex Rivera", availabilityPercentage: 100, location: "Remote", createdAt: now, updatedAt: now },
];

export const fallbackEngineerSkills: EngineerSkill[] = [
  { engineerId: "eng-1", skillId: "sk-1", rating: 5 }, { engineerId: "eng-1", skillId: "sk-4", rating: 4 }, { engineerId: "eng-1", skillId: "sk-5", rating: 4 },
  { engineerId: "eng-2", skillId: "sk-2", rating: 5 }, { engineerId: "eng-2", skillId: "sk-3", rating: 4 }, { engineerId: "eng-2", skillId: "sk-1", rating: 3 },
  { engineerId: "eng-3", skillId: "sk-1", rating: 4 }, { engineerId: "eng-3", skillId: "sk-4", rating: 3 },
  { engineerId: "eng-4", skillId: "sk-7", rating: 4 }, { engineerId: "eng-4", skillId: "sk-1", rating: 3 },
  { engineerId: "eng-5", skillId: "sk-2", rating: 4 }, { engineerId: "eng-5", skillId: "sk-3", rating: 3 },
  { engineerId: "eng-6", skillId: "sk-2", rating: 3 }, { engineerId: "eng-6", skillId: "sk-1", rating: 3 },
  { engineerId: "eng-7", skillId: "sk-4", rating: 5 }, { engineerId: "eng-7", skillId: "sk-6", rating: 4 },
  { engineerId: "eng-8", skillId: "sk-3", rating: 4 }, { engineerId: "eng-8", skillId: "sk-8", rating: 3 },
  { engineerId: "eng-9", skillId: "sk-7", rating: 5 }, { engineerId: "eng-9", skillId: "sk-1", rating: 4 },
  { engineerId: "eng-10", skillId: "sk-6", rating: 4 }, { engineerId: "eng-10", skillId: "sk-4", rating: 3 },
];

export const fallbackTrackSkills: TrackSkillRequirement[] = [
  { trackId: "trk-1", skillId: "sk-1", requiredRating: 4, effortWeight: 2 },
  { trackId: "trk-1", skillId: "sk-4", requiredRating: 3, effortWeight: 1 },
  { trackId: "trk-1", skillId: "sk-5", requiredRating: 4, effortWeight: 1 },
  { trackId: "trk-4", skillId: "sk-3", requiredRating: 4, effortWeight: 2 },
  { trackId: "trk-4", skillId: "sk-2", requiredRating: 3, effortWeight: 1 },
  { trackId: "trk-4", skillId: "sk-8", requiredRating: 3, effortWeight: 1 },
  { trackId: "trk-7", skillId: "sk-7", requiredRating: 4, effortWeight: 2 },
  { trackId: "trk-7", skillId: "sk-4", requiredRating: 3, effortWeight: 1 },
];

export const fallbackWeeklyStatuses: WeeklyStatus[] = [
  {
    id: "ws-1", trackId: "trk-1", weekStartDate: weekStart, status: "GREEN",
    progressUpdate: "Canary deployment complete for 3 services",
    completedThisWeek: ["Canary deployment for 3 core services", "Load test at 2x peak"],
    plannedNextWeek: ["Migrate remaining 5 services", "Finalize rollback runbook"],
    risks: [], blockers: [], decisionsNeeded: [],
    leadershipAsk: "Need SRE review slot by Friday",
    updatedBy: "Alex Rivera", createdAt: now, updatedAt: now,
  },
  {
    id: "ws-2", trackId: "trk-4", weekStartDate: weekStart, status: "AMBER",
    progressUpdate: "Payment done, iOS edge cases remain",
    completedThisWeek: ["Payment SDK integration complete", "A/B framework wired"],
    plannedNextWeek: ["Accessibility audit fixes", "iOS edge-case testing"],
    risks: ["Conversion targets at risk if slip past Aug 30"],
    blockers: ["Design system tokens not finalized for dark mode"],
    decisionsNeeded: ["Design lead decision on token naming"],
    leadershipAsk: "1 additional mobile engineer for 2 sprints",
    updatedBy: "Jordan Kim", createdAt: now, updatedAt: now,
  },
  {
    id: "ws-3", trackId: "trk-7", weekStartDate: weekStart, status: "RED",
    progressUpdate: "Blocked on infra budget and access",
    completedThisWeek: ["Defined SLA targets with data team"],
    plannedNextWeek: ["Auto-retry with dead-letter queue", "Recovery dashboard"],
    risks: ["Downstream analytics features depend on this"],
    blockers: ["Kafka cluster upgrade blocked on budget", "Missing prod data lake access"],
    decisionsNeeded: ["VP Eng approval for infra spend ($45K)"],
    leadershipAsk: "Data platform team to grant prod read access",
    updatedBy: "Alex Rivera", createdAt: now, updatedAt: now,
  },
  {
    id: "ws-4", trackId: "trk-2", weekStartDate: weekStart, status: "GREY",
    progressUpdate: "Vendor evaluation complete",
    completedThisWeek: ["Vendor evaluation matrix complete"],
    plannedNextWeek: ["POC with top 2 vendors", "Define migration timeline"],
    risks: [], blockers: [], decisionsNeeded: [],
    leadershipAsk: null,
    updatedBy: "Alex Rivera", createdAt: now, updatedAt: now,
  },
  {
    id: "ws-5", trackId: "trk-3", weekStartDate: weekStart, status: "GREEN",
    progressUpdate: "Build times down 40%",
    completedThisWeek: ["Parallelized test suite", "Cached dependency layers"],
    plannedNextWeek: ["Roll out to all repos", "Document runbook"],
    risks: [], blockers: [], decisionsNeeded: [],
    leadershipAsk: null,
    updatedBy: "Morgan Lee", createdAt: now, updatedAt: now,
  },
];

export const fallbackRisks: Risk[] = [
  { id: "risk-1", trackId: "trk-7", title: "Infra budget not approved", severity: "CRITICAL", owner: "Alex Rivera", status: "open", mitigation: "Escalate to VP Eng", dueDate: new Date("2026-07-05"), createdAt: now, updatedAt: now },
  { id: "risk-2", trackId: "trk-4", title: "Mobile capacity constraint", severity: "HIGH", owner: "Jordan Kim", status: "open", mitigation: "Request temp headcount", dueDate: new Date("2026-07-10"), createdAt: now, updatedAt: now },
  { id: "risk-3", trackId: "trk-4", title: "Conversion target miss", severity: "MEDIUM", owner: "Taylor Brooks", status: "open", mitigation: "Scope reduction discussion", dueDate: new Date("2026-07-15"), createdAt: now, updatedAt: now },
  { id: "risk-4", trackId: "trk-1", title: "SRE review bottleneck", severity: "LOW", owner: "Morgan Lee", status: "open", mitigation: "Pre-schedule review slots", dueDate: new Date("2026-07-04"), createdAt: now, updatedAt: now },
];

export const fallbackBlockers: Blocker[] = [
  { id: "blk-1", trackId: "trk-7", title: "Kafka cluster upgrade blocked on budget", owner: "Alex Rivera", blockedSince: new Date("2026-06-16"), status: "open", escalationNeeded: true, createdAt: now, updatedAt: now },
  { id: "blk-2", trackId: "trk-7", title: "Missing prod data lake access", owner: "Quinn Martinez", blockedSince: new Date("2026-06-20"), status: "open", escalationNeeded: true, createdAt: now, updatedAt: now },
  { id: "blk-3", trackId: "trk-4", title: "Design system tokens not finalized", owner: "Casey Nguyen", blockedSince: new Date("2026-06-25"), status: "open", escalationNeeded: false, createdAt: now, updatedAt: now },
];
